import {useEffect,useState} from 'react';
import {Plus,Pencil,Trash2,Box,Thermometer,Ruler,Wifi,Power,AlertTriangle} from 'lucide-react';
import {createStorage,updateStorage,deleteStorage} from '../api/client';
import Storage3D from '../components/Storage3D';

export default function Storage({locations,setLocations,products}){
 const [adding,setAdding]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selectedId,setSelectedId]=useState(null),[type,setType]=useState('Refrigerator');
 const [outage,setOutage]=useState(false),[demoTemp,setDemoTemp]=useState(null),[outageSeconds,setOutageSeconds]=useState(0);
 const productCount=id=>products.filter(p=>String(p.locationId||p.storageLocationId)===String(id)).length;
 const selected=locations.find(x=>String(x.id)===String(selectedId))||locations[0]||null;
 const selectedProducts=selected?products.filter(p=>String(p.locationId||p.storageLocationId)===String(selected.id)):[];
 const baseTemp=selected?.temperature!=null?Number(selected.temperature):(String(selected?.type||'').toLowerCase().includes('freezer')?-18:4);
 const currentDemoTemp=outage&&demoTemp!=null?demoTemp:baseTemp;

 useEffect(()=>{if(!outage)return;const timer=setInterval(()=>{setOutageSeconds(v=>{const next=v+1;if(next>=12){setOutage(false);setDemoTemp(null);setMessage('Power restored. Storage temperature is recovering.');return 0}return next});setDemoTemp(v=>{const start=baseTemp;const step=String(selected?.type||'').toLowerCase().includes('freezer')?1.8:0.9;return Math.min(start+step*(outageSeconds+1),String(selected?.type||'').toLowerCase().includes('freezer')?-5:11)})},1000);return()=>clearInterval(timer)},[outage,baseTemp,selected?.type,outageSeconds]);

 const startOutage=()=>{if(!selected)return;setOutageSeconds(0);setDemoTemp(baseTemp);setOutage(true);setMessage(`DEMO: Power outage started in ${selected.name}. Temperature will rise for 12 seconds.`)};
 const stopOutage=()=>{setOutage(false);setDemoTemp(null);setOutageSeconds(0);setMessage('Power restored. Storage temperature is recovering.')};
 const submit=async e=>{e.preventDefault();const fd=new FormData(e.target);const choice=String(fd.get('type')||'Refrigerator');const custom=String(fd.get('custom_type')||'').trim();const payload={name:String(fd.get('name')||'').trim(),type:choice==='Other'?custom:choice,sensor_enabled:fd.get('sensor_enabled')==='on',width:fd.get('width')||null,height:fd.get('height')||null,depth:fd.get('depth')||null};if(!payload.name)return;if(choice==='Other'&&!custom){setMessage('Enter the custom storage type.');return}setBusy(true);setMessage('');try{const created=await createStorage(payload);setLocations(x=>[...x,created]);setSelectedId(created.id);setAdding(false);setMessage(`${created.name||payload.name} was added successfully.`)}catch(err){setMessage(err.message||'Unable to create storage location.')}finally{setBusy(false)}};
 const edit=async item=>{const name=window.prompt('Storage name',item.name);if(!name||name.trim()===item.name)return;try{const updated=await updateStorage(item.id,{name:name.trim()});setLocations(x=>x.map(v=>v.id===item.id?updated:v));setMessage('Storage location updated.')}catch(err){setMessage(err.message||'Unable to update storage location.')}};
 const remove=async item=>{if(productCount(item.id)){setMessage(`${item.name} contains products. Move them before deleting.`);return}if(!window.confirm(`Delete ${item.name}?`))return;try{await deleteStorage(item.id);setLocations(x=>x.filter(v=>v.id!==item.id));setSelectedId(null);setMessage('Storage location deleted.')}catch(err){setMessage(err.message||'Unable to delete storage location.')}};
 return <div className="page settings">
  <section className="setting-section"><div className="section-heading"><div><p className="eyebrow">STORAGE MANAGEMENT</p><h2>Storage Locations</h2><p>Manage the refrigerators, freezers and shelves monitored by FreshGuard.</p></div><button type="button" className="primary" onClick={()=>setAdding(true)}><Plus size={17}/> Add Storage</button></div>{message&&<div className="success">{message}</div>}</section>
  <section className="setting-section">{locations.length===0?<div className="empty-state"><Box size={28}/><h3>No storage locations yet</h3><p>Add your first storage location to start monitoring temperature and inventory placement.</p><button className="primary" onClick={()=>setAdding(true)}><Plus size={16}/> Add Storage</button></div>:<div className="manage-grid storage-grid">{locations.map(item=><article key={item.id} onClick={()=>{setSelectedId(item.id);setOutage(false);setDemoTemp(null)}} style={{cursor:'pointer',outline:String(selected?.id)===String(item.id)?'2px solid #217a58':'none'}}><div><strong>{item.name}</strong><small><Box size={13}/> {item.type||'Storage'} · {productCount(item.id)} products</small><small><Thermometer size={13}/> {String(selected?.id)===String(item.id)&&outage?`${currentDemoTemp.toFixed(1)}°C · POWER OUTAGE`:(item.temperature!=null?`${item.temperature}°C`:'No recent temperature')} · {item.sensor||item.sensorEnabled?'Sensor connected':'Sensor not enabled'}</small>{(item.width||item.height||item.depth)&&<small><Ruler size={13}/> {item.width??'—'} × {item.height??'—'} × {item.depth??'—'}</small>}</div><span><button aria-label={`Edit ${item.name}`} onClick={e=>{e.stopPropagation();edit(item)}}><Pencil size={16}/></button><button aria-label={`Delete ${item.name}`} onClick={e=>{e.stopPropagation();remove(item)}}><Trash2 size={16}/></button></span></article>)}</div>}</section>
  {selected&&<section className="setting-section">
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap',marginBottom:16}}><div><p className="eyebrow">DEMO CONTROLS</p><h2 style={{marginBottom:4}}>Power outage simulation</h2><p style={{margin:0,color:'#718078'}}>Demonstrate how a refrigeration failure can push storage outside its safe range.</p></div>{outage?<button type="button" onClick={stopOutage} style={{border:'1px solid #c65353',background:'#fff3f3',color:'#a43c3c',padding:'10px 14px',borderRadius:10,fontWeight:700,display:'flex',alignItems:'center',gap:7}}><Power size={16}/> Restore power</button>:<button type="button" className="primary" onClick={startOutage}><Power size={16}/> Simulate power outage</button>}</div>
    {outage&&<div style={{padding:14,borderRadius:12,background:'#fff2f2',border:'1px solid #f0c4c4',display:'flex',alignItems:'center',gap:10,marginBottom:16}}><AlertTriangle size={20}/><div><strong>POWER OUTAGE — DEMO</strong><div style={{fontSize:13}}>Temperature: {currentDemoTemp.toFixed(1)}°C · {12-outageSeconds}s remaining · sensor trend is rising</div></div></div>}
    <Storage3D storage={selected} products={selectedProducts}/>
  </section>}
  <section className="setting-section"><p className="eyebrow">MONITORING</p><h2>Storage is the source of truth</h2><p>Products, sensor readings and risk assessments are linked to these backend storage locations.</p><div className="module-list"><span><Wifi size={15}/> Live sensor status</span><span><Thermometer size={15}/> Temperature monitoring</span><span><Box size={15}/> Product placement</span><span><Power size={15}/> Power-outage simulation</span></div></section>
  {adding&&<div className="modal-backdrop"><form className="modal" onSubmit={submit}><h2>Add storage location</h2><label>Name<input name="name" placeholder="e.g. Main Refrigerator" required autoFocus/></label><label>Type<select name="type" value={type} onChange={e=>setType(e.target.value)}><option>Refrigerator</option><option>Freezer</option><option>Shelf</option><option>Other</option></select></label>{type==='Other'&&<label>Storage type name<input name="custom_type" placeholder="e.g. Cold Room, Display Chiller" autoFocus/></label>}<label><input type="checkbox" name="sensor_enabled" defaultChecked/> Sensor enabled</label><div className="form-grid"><label>Width<input name="width" type="number" min="0" step="any" placeholder="cm"/></label><label>Height<input name="height" type="number" min="0" step="any" placeholder="cm"/></label><label>Depth<input name="depth" type="number" min="0" step="any" placeholder="cm"/></label></div><div className="modal-actions"><button type="button" onClick={()=>setAdding(false)} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy?'Creating…':'Create Storage'}</button></div></form></div>}
 </div>;
}
